apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: query
spec:
  ports:
  - name: jaeger-query
    port: 80
    protocol: TCP
    targetPort: 16686
  - name: jaeger-query-prometheus
    port: 16687
    protocol: TCP
    targetPort: 16687
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: query
  type: LoadBalancer