// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PingBClient is the client API for PingB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingBClient interface {
	PingB(ctx context.Context, in *PingBReq, opts ...grpc.CallOption) (*PingBResponse, error)
}

type pingBClient struct {
	cc grpc.ClientConnInterface
}

func NewPingBClient(cc grpc.ClientConnInterface) PingBClient {
	return &pingBClient{cc}
}

func (c *pingBClient) PingB(ctx context.Context, in *PingBReq, opts ...grpc.CallOption) (*PingBResponse, error) {
	out := new(PingBResponse)
	err := c.cc.Invoke(ctx, "/pb.PingB/PingB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingBServer is the server API for PingB service.
// All implementations must embed UnimplementedPingBServer
// for forward compatibility
type PingBServer interface {
	PingB(context.Context, *PingBReq) (*PingBResponse, error)
	mustEmbedUnimplementedPingBServer()
}

// UnimplementedPingBServer must be embedded to have forward compatible implementations.
type UnimplementedPingBServer struct {
}

func (UnimplementedPingBServer) PingB(context.Context, *PingBReq) (*PingBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingB not implemented")
}
func (UnimplementedPingBServer) mustEmbedUnimplementedPingBServer() {}

// UnsafePingBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingBServer will
// result in compilation errors.
type UnsafePingBServer interface {
	mustEmbedUnimplementedPingBServer()
}

func RegisterPingBServer(s grpc.ServiceRegistrar, srv PingBServer) {
	s.RegisterService(&PingB_ServiceDesc, srv)
}

func _PingB_PingB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingBReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingBServer).PingB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PingB/PingB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingBServer).PingB(ctx, req.(*PingBReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PingB_ServiceDesc is the grpc.ServiceDesc for PingB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PingB",
	HandlerType: (*PingBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingB",
			Handler:    _PingB_PingB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ping.b.proto",
}
