// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/ping.a.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingAReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Now  int64  `protobuf:"varint,1,opt,name=now,proto3" json:"now,omitempty"`
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *PingAReq) Reset() {
	*x = PingAReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ping_a_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingAReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingAReq) ProtoMessage() {}

func (x *PingAReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_ping_a_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingAReq.ProtoReflect.Descriptor instead.
func (*PingAReq) Descriptor() ([]byte, []int) {
	return file_api_ping_a_proto_rawDescGZIP(), []int{0}
}

func (x *PingAReq) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *PingAReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type PingAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Now int64 `protobuf:"varint,1,opt,name=now,proto3" json:"now,omitempty"`
}

func (x *PingAResponse) Reset() {
	*x = PingAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ping_a_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingAResponse) ProtoMessage() {}

func (x *PingAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ping_a_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingAResponse.ProtoReflect.Descriptor instead.
func (*PingAResponse) Descriptor() ([]byte, []int) {
	return file_api_ping_a_proto_rawDescGZIP(), []int{1}
}

func (x *PingAResponse) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

var File_api_ping_a_proto protoreflect.FileDescriptor

var file_api_ping_a_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x30, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x6e, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0x21, 0x0a, 0x0d, 0x50, 0x69, 0x6e, 0x67,
	0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x6f, 0x77, 0x32, 0x33, 0x0a, 0x05, 0x50,
	0x69, 0x6e, 0x67, 0x41, 0x12, 0x2a, 0x0a, 0x05, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x12, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79,
	0x65, 0x71, 0x6f, 0x77, 0x6e, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e,
	0x67, 0x2d, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ping_a_proto_rawDescOnce sync.Once
	file_api_ping_a_proto_rawDescData = file_api_ping_a_proto_rawDesc
)

func file_api_ping_a_proto_rawDescGZIP() []byte {
	file_api_ping_a_proto_rawDescOnce.Do(func() {
		file_api_ping_a_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ping_a_proto_rawDescData)
	})
	return file_api_ping_a_proto_rawDescData
}

var file_api_ping_a_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_ping_a_proto_goTypes = []interface{}{
	(*PingAReq)(nil),      // 0: pb.PingAReq
	(*PingAResponse)(nil), // 1: pb.PingAResponse
}
var file_api_ping_a_proto_depIdxs = []int32{
	0, // 0: pb.PingA.PingA:input_type -> pb.PingAReq
	1, // 1: pb.PingA.PingA:output_type -> pb.PingAResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ping_a_proto_init() }
func file_api_ping_a_proto_init() {
	if File_api_ping_a_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ping_a_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingAReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ping_a_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ping_a_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ping_a_proto_goTypes,
		DependencyIndexes: file_api_ping_a_proto_depIdxs,
		MessageInfos:      file_api_ping_a_proto_msgTypes,
	}.Build()
	File_api_ping_a_proto = out.File
	file_api_ping_a_proto_rawDesc = nil
	file_api_ping_a_proto_goTypes = nil
	file_api_ping_a_proto_depIdxs = nil
}
